#!/bin/bash
userfile="$1"
aliasfile="$2"

users=($(cat $userfile | cut -d\, -f 1,2,3))
alias=($(cat $aliasfile))

for line in "${users[@]}"
do
  IFS="," read -ra userdata <<< "$line"
    gam create user ${userdata[0]} firstname ${userdata[1]} lastname ${userdata[2]}
    echo "gam create user ${userdata[0]} firstname ${userdata[1]} lastname ${userdata[2]}"
done

for alias in "${alias[@]}"
do
  IFS="," read -ra aliasdata <<< "$alias"
    gam create alias ${aliasdata[0]} target ${aliasdata[1]} type ${aliasdata[2]}
    echo "gam create alias ${aliasdata[0]} target ${aliasdata[1]} type ${aliasdata[2]}"
done
